"""modify

Revision ID: 01c468b6cb27
Revises: e5bafda87a31
Create Date: 2025-05-05 07:43:32.722667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c468b6cb27'
down_revision = 'e5bafda87a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 