"""next gen

Revision ID: 1ad7e7a47c03
Revises: 993d9f9a4f71
Create Date: 2025-05-05 09:54:55.508214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad7e7a47c03'
down_revision = '993d9f9a4f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 