"""Initial migration

Revision ID: 3392694c9f65
Revises: 9910e931c049
Create Date: 2025-05-05 04:38:11.670532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3392694c9f65'
down_revision = '9910e931c049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 