"""Add original_global_collection_name to conversations

Revision ID: 33fdaf209fe1
Revises: 96da24629e52
Create Date: 2025-05-27 13:38:46.440926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33fdaf209fe1'
down_revision = '96da24629e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('original_global_collection_name', sa.String(), nullable=True, comment='Name of the global collection when conversation was initiated'))
    op.alter_column('conversations', 'display_file_id',
               existing_type=sa.INTEGER(),
               comment='File to display in the chat panel',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'display_file_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='File to display in the chat panel',
               existing_nullable=True)
    op.drop_column('conversations', 'original_global_collection_name')
    # ### end Alembic commands ### 