"""modify again

Revision ID: 3bacce2a7dd7
Revises: b197a02788b7
Create Date: 2025-05-05 07:49:15.763372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bacce2a7dd7'
down_revision = 'b197a02788b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 