"""add_temporary_password_fields

Revision ID: 4f6b1fa00461
Revises: 8c13a233f5b6
Create Date: 2025-06-12 07:23:53.412333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6b1fa00461'
down_revision = '8c13a233f5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_temporary_password', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('temp_password_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('must_reset_password', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_reset_password')
    op.drop_column('users', 'temp_password_expires_at')
    op.drop_column('users', 'is_temporary_password')
    # ### end Alembic commands ### 