"""simplify config

Revision ID: 5b13dd7648c1
Revises: 8579d4dad10b
Create Date: 2025-05-05 06:07:49.616198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b13dd7648c1'
down_revision = '8579d4dad10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_configs', 'presence_penalty')
    op.drop_column('llm_configs', 'n')
    op.drop_column('llm_configs', 'context_window')
    op.drop_column('llm_configs', 'is_active')
    op.drop_column('llm_configs', 'extra_params')
    op.drop_column('llm_configs', 'description')
    op.drop_column('llm_configs', 'frequency_penalty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_configs', sa.Column('frequency_penalty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('llm_configs', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('llm_configs', sa.Column('extra_params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('llm_configs', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('llm_configs', sa.Column('context_window', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('llm_configs', sa.Column('n', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('llm_configs', sa.Column('presence_penalty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 