"""unified_config_table

Revision ID: 6ee941de99bf
Revises: d86951da6acb
Create Date: 2025-05-08 04:32:00.135847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee941de99bf'
down_revision = 'd86951da6acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_config', sa.Column('value_type', sa.String(), nullable=False))
    op.add_column('admin_config', sa.Column('category', sa.String(), nullable=False))
    op.alter_column('admin_config', 'value',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('collections', 'is_global_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collections', 'is_global_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('admin_config', 'value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('admin_config', 'category')
    op.drop_column('admin_config', 'value_type')
    # ### end Alembic commands ### 