"""add_enable_thinking_to_llm_config

Revision ID: 7f9b5b6f8faf
Revises: 33fdaf209fe1
Create Date: 2025-05-28 07:10:05.037904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f9b5b6f8faf'
down_revision = '33fdaf209fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the enable_thinking column, not the id column (it should already exist)
    op.add_column('llm_config', sa.Column('enable_thinking', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_column('messages', 'retrieved_doc_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('retrieved_doc_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Stores document IDs used in retrieval'))
    op.drop_column('llm_config', 'enable_thinking')
    # ### end Alembic commands ### 