"""Initial migration

Revision ID: 84ec5fdd58b9
Revises: 3392694c9f65
Create Date: 2025-05-05 04:41:23.949073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ec5fdd58b9'
down_revision = '3392694c9f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 