"""new set

Revision ID: 8579d4dad10b
Revises: fe7f68983304
Create Date: 2025-05-05 06:04:28.935978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8579d4dad10b'
down_revision = 'fe7f68983304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 