"""modify auth

Revision ID: 858a412253ee
Revises: 3bacce2a7dd7
Create Date: 2025-05-05 08:54:25.464684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858a412253ee'
down_revision = '3bacce2a7dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 