"""remove_vector_ids_column

Revision ID: 96da24629e52
Revises: a5b24d901c7e
Create Date: 2025-05-27 04:27:30.251475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96da24629e52'
down_revision = 'a5b24d901c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_files', 'vector_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_files', sa.Column('vector_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 