"""Initial migration

Revision ID: 9910e931c049
Revises: 88c684eac0b2
Create Date: 2025-05-05 04:26:18.322706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9910e931c049'
down_revision = '88c684eac0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 