"""modify again

Revision ID: b197a02788b7
Revises: 01c468b6cb27
Create Date: 2025-05-05 07:47:24.074258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b197a02788b7'
down_revision = '01c468b6cb27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 