"""add user role

Revision ID: b3d2d7131fa6
Revises: 5b13dd7648c1
Create Date: 2025-05-05 06:11:20.009084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d2d7131fa6'
down_revision = '5b13dd7648c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_configs', sa.Column('presence_penalty', sa.Float(), nullable=True))
    op.add_column('llm_configs', sa.Column('frequency_penalty', sa.Float(), nullable=True))
    op.add_column('llm_configs', sa.Column('n', sa.Integer(), nullable=True))
    op.add_column('llm_configs', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('llm_configs', sa.Column('context_window', sa.Integer(), nullable=True))
    op.add_column('llm_configs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('llm_configs', sa.Column('extra_params', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'role')
    op.drop_column('llm_configs', 'extra_params')
    op.drop_column('llm_configs', 'description')
    op.drop_column('llm_configs', 'context_window')
    op.drop_column('llm_configs', 'is_active')
    op.drop_column('llm_configs', 'n')
    op.drop_column('llm_configs', 'frequency_penalty')
    op.drop_column('llm_configs', 'presence_penalty')
    # ### end Alembic commands ### 