"""Add conversation types and global collection

Revision ID: d86951da6acb
Revises: 2299131efc52
Create Date: 2025-05-07 12:30:54.236930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86951da6acb'
down_revision = '2299131efc52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_config_id'), 'admin_config', ['id'], unique=False)
    op.create_index(op.f('ix_admin_config_key'), 'admin_config', ['key'], unique=True)
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    
    # Add nullable columns first
    op.add_column('collections', sa.Column('is_global_default', sa.Boolean(), nullable=True))
    op.add_column('conversations', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    
    # Create enum type for conversation_type
    op.execute("CREATE TYPE conversationtype AS ENUM ('REGULAR', 'USER_FILES', 'GLOBAL_COLLECTION')")
    
    # Add columns with default values that can be modified later
    op.add_column('conversations', sa.Column('is_empty', sa.Boolean(), nullable=True))
    op.add_column('conversations', sa.Column('conversation_type', sa.Enum('REGULAR', 'USER_FILES', 'GLOBAL_COLLECTION', name='conversationtype'), nullable=True))
    
    # Add foreign key column
    op.add_column('conversations', sa.Column('linked_global_collection_id', sa.Integer(), nullable=True))
    
    # Set default values for existing records
    op.execute("UPDATE conversations SET is_empty = false")
    op.execute("UPDATE conversations SET conversation_type = 'REGULAR'")
    
    # Set default value for collections.is_global_default
    op.execute("UPDATE collections SET is_global_default = false")
    
    # Now make the columns NOT NULL
    op.alter_column('conversations', 'is_empty', nullable=False)
    op.alter_column('conversations', 'conversation_type', nullable=False)
    op.alter_column('collections', 'is_global_default', nullable=False, server_default='false')
    
    # Create foreign key constraint
    op.create_foreign_key(None, 'conversations', 'collections', ['linked_global_collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'linked_global_collection_id')
    op.drop_column('conversations', 'conversation_type')
    op.drop_column('conversations', 'is_empty')
    op.drop_column('conversations', 'expires_at')
    op.drop_column('collections', 'is_global_default')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_admin_config_key'), table_name='admin_config')
    op.drop_index(op.f('ix_admin_config_id'), table_name='admin_config')
    op.drop_table('admin_config')
    # ### end Alembic commands ### 