"""modify config

Revision ID: e5bafda87a31
Revises: b3d2d7131fa6
Create Date: 2025-05-05 07:19:43.530255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5bafda87a31'
down_revision = 'b3d2d7131fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_configs', 'frequency_penalty')
    op.drop_column('llm_configs', 'n')
    op.drop_column('llm_configs', 'presence_penalty')
    op.drop_column('llm_configs', 'context_window')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_configs', sa.Column('context_window', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('llm_configs', sa.Column('presence_penalty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('llm_configs', sa.Column('n', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('llm_configs', sa.Column('frequency_penalty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 