"""Initial migration

Revision ID: fe7f68983304
Revises: 84ec5fdd58b9
Create Date: 2025-05-05 05:59:56.877190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7f68983304'
down_revision = '84ec5fdd58b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 